/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;
import java.math.BigDecimal;

/**
 *
 * @author vuszi
 */
public class CalcUI extends javax.swing.JFrame {
    
    public static String calcInput="", calcOutput="";
    public static BigDecimal result, temp=BigDecimal.valueOf(0);
    /**
     * Creates new form CalcUI
     */
    public CalcUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        txfResult = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(54, 168, 142));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfResult.setBackground(new java.awt.Color(254, 254, 254));
        txfResult.setFont(new java.awt.Font("Lucida MAC", 0, 36)); // NOI18N
        txfResult.setForeground(new java.awt.Color(103, 103, 103));
        txfResult.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txfResult.setText("0");
        txfResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfResultActionPerformed(evt);
            }
        });
        getContentPane().add(txfResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 90));

        btnPlus.setBackground(new java.awt.Color(225, 234, 231));
        btnPlus.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(78, 78, 78));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, 60));

        btn7.setBackground(new java.awt.Color(225, 234, 231));
        btn7.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(78, 78, 78));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 70, 70));

        btn8.setBackground(new java.awt.Color(225, 234, 231));
        btn8.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(78, 78, 78));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 70, 70));

        btn9.setBackground(new java.awt.Color(225, 234, 231));
        btn9.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(78, 78, 78));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, 70));

        btnDiv.setBackground(new java.awt.Color(225, 234, 231));
        btnDiv.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(78, 78, 78));
        btnDiv.setText("÷");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 70, 60));

        btnMult.setBackground(new java.awt.Color(225, 234, 231));
        btnMult.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btnMult.setForeground(new java.awt.Color(78, 78, 78));
        btnMult.setText("x");
        getContentPane().add(btnMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 70, 60));

        btn4.setBackground(new java.awt.Color(225, 234, 231));
        btn4.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(78, 78, 78));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 70, 70));

        btn5.setBackground(new java.awt.Color(225, 234, 231));
        btn5.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(78, 78, 78));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 70, 70));

        btn6.setBackground(new java.awt.Color(225, 234, 231));
        btn6.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(78, 78, 78));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 70, 70));

        btnAC.setBackground(new java.awt.Color(254, 148, 148));
        btnAC.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btnAC.setForeground(new java.awt.Color(254, 254, 254));
        btnAC.setText("AC");
        getContentPane().add(btnAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 70, 40));

        btn3.setBackground(new java.awt.Color(225, 234, 231));
        btn3.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(78, 78, 78));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 70, 70));

        btn1.setBackground(new java.awt.Color(225, 234, 231));
        btn1.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(78, 78, 78));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 70, 70));

        jButton15.setBackground(new java.awt.Color(225, 234, 231));
        jButton15.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(78, 78, 78));
        jButton15.setText(",");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, 70));

        btn0.setBackground(new java.awt.Color(225, 234, 231));
        btn0.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(78, 78, 78));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 70, 70));

        jButton17.setBackground(new java.awt.Color(86, 189, 225));
        jButton17.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(254, 254, 254));
        jButton17.setText("=");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 70, 70));

        btnMinus.setBackground(new java.awt.Color(225, 234, 231));
        btnMinus.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(78, 78, 78));
        btnMinus.setText("-");
        getContentPane().add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, 60));

        btn2.setBackground(new java.awt.Color(225, 234, 231));
        btn2.setFont(new java.awt.Font("Lucida MAC", 0, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(78, 78, 78));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, 70));

        jMenuBar1.setBackground(new java.awt.Color(76, 242, 186));
        jMenuBar1.setBorder(null);

        jMenu1.setText("File");

        jMenuItem1.setText("Ac");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("New Session");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mniAbout.setText("About.");
        jMenu2.add(mniAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        calcInput = calcInput+"1";
        calcOutput =calcOutput +"1";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        calcInput = calcInput+"0";
        calcOutput =calcOutput+"0";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn0ActionPerformed

    private void txfResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfResultActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        calcInput = calcInput+"2";
        calcOutput =calcOutput +"2";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        calcInput = calcInput+"3";
        calcOutput =calcOutput +"3";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        calcInput = calcInput+"4";
        calcOutput =calcOutput +"4";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        calcInput = calcInput+"5";
        calcOutput =calcOutput+"5";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        calcInput = calcInput+"6";
        calcOutput =calcOutput+"6";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        calcInput = calcInput+"7";
        calcOutput =calcOutput+"7";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        calcInput = calcInput+"8";
        calcOutput =calcOutput+"8";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        calcInput = calcInput+"9";
        calcOutput =calcOutput+"9";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_btn9ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        calcInput = calcInput+".";
        calcOutput =calcOutput+".";
        txfResult.setText(calcOutput);
        result = BigDecimal.valueOf(Double.parseDouble(calcInput));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        
        temp=new Operations().sum(temp, result);
        result=temp;
        calcOutput = calcOutput+"+";
        calcInput="";
        txfResult.setText(calcOutput);
        
    }//GEN-LAST:event_btnPlusActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        
        temp=new Operations().sum(temp,result);
        result=BigDecimal.valueOf(0);
        calcInput="";
        calcOutput=""+temp;
        txfResult.setText(""+temp);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btn0;
    protected javax.swing.JButton btn1;
    protected javax.swing.JButton btn2;
    protected javax.swing.JButton btn3;
    protected javax.swing.JButton btn4;
    protected javax.swing.JButton btn5;
    protected javax.swing.JButton btn6;
    protected javax.swing.JButton btn7;
    protected javax.swing.JButton btn8;
    protected javax.swing.JButton btn9;
    protected javax.swing.JButton btnAC;
    protected javax.swing.JButton btnDiv;
    protected javax.swing.JButton btnMinus;
    protected javax.swing.JButton btnMult;
    protected javax.swing.JButton btnPlus;
    protected javax.swing.JButton jButton15;
    protected javax.swing.JButton jButton17;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem mniAbout;
    protected javax.swing.JTextField txfResult;
    // End of variables declaration//GEN-END:variables
}
